# Generated by Django 3.1.3 on 2021-06-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210531_1959'),
        ('tweets', '0002_auto_20210426_0742'),
    ]

    operations = [
    ]
